export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0F0F0F] px-8 py-16 max-w-2xl mx-auto">
      <h1 className="text-2xl font-bold text-[#F5F5F5] mb-4">Terms of Service</h1>
      <p className="text-[#888] mb-4">Last updated: April 2025</p>
      <div className="space-y-4 text-[#888] text-sm leading-relaxed">
        <p>
          By using InboxPilot, you agree to these terms. InboxPilot is an AI-powered email
          assistant that helps you manage your inbox.
        </p>
        <h2 className="text-[#F5F5F5] font-semibold text-base mt-6">Permitted use</h2>
        <p>
          You may use InboxPilot for personal and commercial email management. You agree not to use
          the service to send spam, violate others&apos; privacy, or engage in illegal activity.
        </p>
        <h2 className="text-[#F5F5F5] font-semibold text-base mt-6">AI-generated content</h2>
        <p>
          Draft replies and summaries are generated by AI and may contain errors. You are
          responsible for reviewing all content before sending. InboxPilot never sends email
          automatically.
        </p>
        <h2 className="text-[#F5F5F5] font-semibold text-base mt-6">Limitation of liability</h2>
        <p>
          InboxPilot is provided &quot;as is&quot; without warranty. We are not liable for any
          damages arising from use of the service.
        </p>
      </div>
    </div>
  )
}
